name = "leansphincs"
version = "0.1.0"
defaultTargets = ["LeanSphincs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCVio.git"
rev = "cbd4144b51d92da00dd50f05e068b2348fa6e529"

[[lean_lib]]
name = "LeanSphincs"

[[lean_lib]]
name = "LeanSphincsTest"
